#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10 

bspc config normal_border_color "#686868"
bspc config focused_border_color "#f28779"
bspc config active_border_color "#f28779"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a firefox desktop=2 follow=off -o
